/***********************************************************************
Filename   : rvosconfig.h
Description: OS specific configuration
************************************************************************
        Copyright (c) 2001 RADVISION Inc. and RADVISION Ltd.
************************************************************************
NOTICE:
This document contains information that is confidential and proprietary
to RADVISION Inc. and RADVISION Ltd.. No part of this document may be
reproduced in any form whatsoever without written prior approval by
RADVISION Inc. or RADVISION Ltd..

RADVISION Inc. and RADVISION Ltd. reserve the right to revise this
publication and make changes without obligation to notify any person of
such revisions or changes.
***********************************************************************/
#ifndef RV_OSCONFIG_H
#define RV_OSCONFIG_H

/* Include proper files for the OS to be used. */
/* Supported OS's are listed in rvosdefs.h and RV_OS_TYPE */
/* should be set in rvbuildconfig.h (which is generated by */
/* the makefiles. */
#if (RV_OS_TYPE == RV_OS_TYPE_SOLARIS)
#include "rvsolaris.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_LINUX)
#include "rvlinux.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_HPUX)
#include "rvhpux.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_TRU64)
#include "rvtru64.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_UNIXWARE)
#include "rvunixware.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_WIN32)
#include "rvwin32.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_WINCE)
#include "rvwince.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_VXWORKS)
#include "rvvxworks.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_PSOS)
#include "rvpsos.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_OSE)
#include "rvose.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_NUCLEUS)
#include "rvnucleus.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_SYMBIAN)
#include "rvsymbian.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_MOPI)
#include "rvmopi.h"
#elif (RV_OS_TYPE == RV_OS_TYPE_INTEGRITY)
#include "rvintegrity.h"
#else
#error RV_OS_TYPE not set properly
#endif

#endif /* RV_OSCONFIG_H */

